#include "animation.h"

#include "sprites_generated.h"

const Sprite ANIMATION_PLAYER_STILL_FRAMES[ANIMATION_PLAYER_STILL_LENGTH] = {
	SPRITE_PLAYER_JUMP_0000,
};

const Sprite ANIMATION_PLAYER_RUN_FRAMES[ANIMATION_PLAYER_RUN_LENGTH] = {
	SPRITE_PLAYER_RUN_0000,
	SPRITE_PLAYER_RUN_0001,
	SPRITE_PLAYER_RUN_0002,
	SPRITE_PLAYER_RUN_0003,
};

// clang-format off
const Sprite ANIMATION_PLAYER_JUMP_FRAMES[ANIMATION_PLAYER_JUMP_LENGTH] = {
	SPRITE_PLAYER_JUMP_0000,
	SPRITE_PLAYER_JUMP_0001,
	SPRITE_PLAYER_JUMP_0002,
	SPRITE_PLAYER_JUMP_0003,
	SPRITE_PLAYER_JUMP_0004,
};
// clang-format on

// clang-format off
const Sprite ANIMATION_PLAYER_SPIN_FRAMES[ANIMATION_PLAYER_SPIN_LENGTH] = {
	SPRITE_PLAYER_SPIN_0000,
	SPRITE_PLAYER_SPIN_0001,
	SPRITE_PLAYER_SPIN_0002,
	SPRITE_PLAYER_SPIN_0003,
	SPRITE_PLAYER_SPIN_0004,
	SPRITE_PLAYER_SPIN_0005,
	SPRITE_PLAYER_SPIN_0006,
	SPRITE_PLAYER_SPIN_0007,
	SPRITE_PLAYER_SPIN_0008,
	SPRITE_PLAYER_SPIN_0009,
	SPRITE_PLAYER_SPIN_0010,
	SPRITE_PLAYER_SPIN_0011,
	SPRITE_PLAYER_SPIN_0012,
};
// clang-format on

const Sprite ANIMATION_WALKER_IDLE_FRAMES[ANIMATION_WALKER_IDLE_LENGTH] = {
	SPRITE_WALKER_IDLE_0000,
	SPRITE_WALKER_IDLE_0001,
	SPRITE_WALKER_IDLE_0002,
	SPRITE_WALKER_IDLE_0003,
};

// clang-format off
const Sprite* ANIMATIONS[ANIMATIONS_LENGTH] = {
	ANIMATION_PLAYER_STILL_FRAMES,
	ANIMATION_PLAYER_RUN_FRAMES,
	ANIMATION_PLAYER_JUMP_FRAMES,
	ANIMATION_PLAYER_SPIN_FRAMES,
	ANIMATION_WALKER_IDLE_FRAMES,
};
// clang-format on
