#pragma once

#define ANIMATION_PLAYER_RUN 0
#define ANIMATION_PLAYER_RUN_LENGTH 4
#define ANIMATION_PLAYER_RUN_FRAME_DURATION 0.18f
extern const char* ANIMATION_PLAYER_RUN_FRAMES[ANIMATION_PLAYER_RUN_LENGTH];

#define ANIMATION_PLAYER_JUMP 1
#define ANIMATION_PLAYER_JUMP_LENGTH 5
#define ANIMATION_PLAYER_JUMP_FRAME_DURATION 0.075f
extern const char* ANIMATION_PLAYER_JUMP_FRAMES[ANIMATION_PLAYER_JUMP_LENGTH];

#define ANIMATION_PLAYER_SPIN 2
#define ANIMATION_PLAYER_SPIN_LENGTH 13
#define ANIMATION_PLAYER_SPIN_FRAME_DURATION 0.1f
extern const char* ANIMATION_PLAYER_SPIN_FRAMES[ANIMATION_PLAYER_SPIN_LENGTH];

#define ANIMATION_WALKER_IDLE 3
#define ANIMATION_WALKER_IDLE_LENGTH 4
#define ANIMATION_WALKER_IDLE_FRAME_DURATION 0.2f
extern const char* ANIMATION_WALKER_IDLE_FRAMES[ANIMATION_WALKER_IDLE_LENGTH];

#define ANIMATIONS_LENGTH 4
extern const char** ANIMATIONS[ANIMATIONS_LENGTH];
